<div>
    <h1>Buy random product from this category!</h1>

    <p>
        <button type="button" title="<?php echo $this->__('Buy Random') ?>" class="button btn-cart"
                onclick="setLocation('<?php echo $this->getAddRandToCartUrl() ?>')">
            <span>
                <span>
                    <?php echo $this->__('Buy Random')  ?>
                </span>
            </span>
        </button>
    </p>
</div>