<?php
/**
 *
 * @category    Nayjest
 * @package     Nayjest_BuyRandomProduct
 * @copyright   Copyright (c) 2013 Vitalii Stepanenko
 * @author      Vitalii Stepanenko <mail@vitaliy.in>
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div>
    <h1>Buy random product from this category!</h1>

    <p>
        <button type="button" title="<?php echo $this->__('Add random product to cart') ?>" class="button btn-cart"
                onclick="setLocation('<?php echo $this->getAddRandToCartUrl() ?>')">
            <span>
                <span>
                    <?php echo $this->__('Add random product to cart')  ?>
                </span>
            </span>
        </button>
    </p>
</div>